spring:
  datasource:
    url: jdbc:h2:mem:gmgtestdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  flyway:
    enabled: false

kakao:
  map:
    api:
      key: ${KAKAO_MAP_API_KEY}

google:
  maps:
    api:
      base-url: https://places.googleapis.com
      key: ${GOOGLE_MAPS_API_KEY}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus, httptrace
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      access: read_only
  metrics:
    tags:
      application: gmg
      environment: ${spring.profiles.active}
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /api-docs

logging:
  config: classpath:logback/logback-local.xml
  level:
    eusyaeusya.gmg: info #필요시 info, trace
    org.hibernate.sql: debug #SQL 쿼리 로깅