spring:
  profiles:
    active: local
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

kakao:
  map:
    api:
      base-url: https://dapi.kakao.com
      category-group-code: FD6,CE7

management-config:
  allowed-ip: ${ACTUATOR_ALLOWED_IP:127.0.0.1}

management:
  tracing:
    sampling:
      probability: 1.0
  observations:
    key-values:
      application: ${spring.application.name:gmg}